### ISSUE TITLE
"Code list" vs "use of a code list" in Section 1.1

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Code-Lists-Spec#10]
[1.1. Code list example](https://rawgit.com/NIEM/NIEM-Code-Lists-Spec/4.0beta1/niem-code-lists-spec.html#section_1.1)

The first paragraph and the first bullet under "In this example" call Table 1-1 a "code list".

> ...an example of a code list...a code list for vehicle makes and models...the code list is the table...

The following sentence (appears in the spec after the bulleted list) calls Table 1-1 a "use of a code list".  

> What we see above is a **use of a** code list, but there are things missing; in order to make code lists and their uses machine-readable and verifiable, this specification provides:

**Comment by webb** [comment]
Text fixed as indicated.
