### ISSUE TITLE
"Machine readable and verifiable" in Section 1.1 might not be enough justification

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Code-Lists-Spec#11]
[1.1. Code list example](https://rawgit.com/NIEM/NIEM-Code-Lists-Spec/4.0beta1/niem-code-lists-spec.html#section_1.1)

> What we see above is a use of a code list, but there are things missing; in order to make code lists and their uses machine-readable and verifiable, this specification provides: ...

Still justifying the need for the spec and the additional complexity at this early point in the document.  Would make the reasons for it a little more specific since XML Schema enums, spreadsheets, and basic CSVs can all provide machine-readable codes that can be used in some manner for verification.

Maybe something like:

> ...in order to make code lists **tables** and their uses **in NIEM consistent,** machine-readable, **and not restricted to the limitations of XML Schema enumerations yet still bindable to instance values**, this specification provides...

There may be better wording for this, but the point behind it is...XML Schema enums support basic code lists, but not code list tables.  You could just throw random code list spreadsheets or CSVs into a release or IEPD, but that wouldn't be consistent.  You could place random code list spreadsheets or CSVs into a designated spot in the release or IEPD, but that wouldn't be enough to tie it to instance values.

**Comment by webb** [comment]
Added a more substantial intro providing goals of the approach.
