### ISSUE TITLE
Repetitive wording in section 1.1

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Code-Lists-Spec#12]
[1.1. Code list example](https://rawgit.com/NIEM/NIEM-Code-Lists-Spec/4.0beta1/niem-code-lists-spec.html#section_1.1)

List item # 1 has repetitive wording:

> 1. Machine-readable formats for code lists. **This specification provides for the use of Genericode, an XML representation, for code lists. It provides for the use of CSV files to represent code lists.** It also provides a foundation for other representations of code lists, to be identified and implemented later.

Suggest combining Genericode and CSV into the same sentence, and maybe specifying what this spec actually provides for their use.  Something like...

> ...This specification provides rules and guidance for the use of Genericode (an XML representation) and CSV files to represent code lists...

**Comment by webb** [comment]
Updated as requested.
