### ISSUE TITLE
Repetitive wording in Section 1.2

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Code-Lists-Spec#13]
[1.2. Machine-readable format for a code list](https://rawgit.com/NIEM/NIEM-Code-Lists-Spec/4.0beta1/niem-code-lists-spec.html#section_1.2)

Paragraph 1:

> This specification provides for representing code lists using CSV files and Genericode files...

Paragraph 2:

> This specification provides for the use of CSV files and Genericode files as code lists.

Suggest removing the first sentence from paragraph 2 and changing the start of the next sentence to "This specification also ..."

**Comment by webb** [comment]
Revised as requested.
