### ISSUE TITLE
Suggest moving structural terms definition reference in section 5

### ISSUE THREAD

**Issue by mikehulme** [NIEM/NIEM-Code-Lists-Spec#6]
Section 5 - I suggest moving the text "The definitions of CSV structural terms are provided by [RFC4180], as noted in Section 2.10, RFC 4180: Comma-separated values (CSV) files, above." from after Rule 5-4, appending it to the section 5 opening paragraph. That way users are alerted to the source of the definitions of the structural terms before they are used.

**Comment by webb** [comment]
Moved text as requested.
