### ISSUE TITLE
Add an example using the well-known column "uri"

### ISSUE THREAD

**Issue by cabralje** [NIEM/NIEM-Code-Lists-Spec#7]
The specification includes a few examples but none demonstrate the new well-known column "uri".  We should provide an example.

**Comment by cabralje** [comment]
Here are a couple examples.  Feel free to adapt as needed.
[BinaryFormatText.txt](https://github.com/NIEM/NIEM-Code-Lists-Spec/files/1167462/BinaryFormatText.txt)
[SignatureProfileCode.txt](https://github.com/NIEM/NIEM-Code-Lists-Spec/files/1167463/SignatureProfileCode.txt)

**Comment by webb** [comment]
in email `DM2PR0401MB12308962D85A52DA858F0F97A9A50@DM2PR0401MB1230.namprd04.prod.outlook.com`, 
Jim provided Genericode examples of code lists with URI columns. His text:

> As promised, here are a couple examples from ECF making use of the new “uri” well-known column. 
 
> The first is a code list of acceptable values for nc:BinaryFormatText that uses the “uri” column to reference the latest information on relevant RFCs for that MIME type.
 
> He second is a code list for document signature profiles which references the relevant specification for a each type of signature.
 
> Feel free to adapt either example for the code list spec as you see fit.

[code-lists-spec-uri-column-examples.zip](https://github.com/NIEM/NIEM-Code-Lists-Spec/files/1209655/code-lists-spec-uri-column-examples.zip)

**Comment by webb** [comment]
Added example from the binaryformat genericode.
