### ISSUE TITLE
Big picture a little unclear in Abstract and Intro sections

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Code-Lists-Spec#8]
Saw some potential questions coming off of the abstract and [intro](https://rawgit.com/NIEM/NIEM-Code-Lists-Spec/4.0beta1/niem-code-lists-spec.html#section_1): 

1.  Does this spec replace or coexist with traditional XML schema code lists?
2.  Are supported code list artifacts just CSVs and Genericode?  Could I use JSON? 
3.  Lead sentence just describes using code list artifacts.  Seems to imply that you could just grab some existing Genericode or CSV code list and use it with your exchange.  Think there should also be a mention of defining the artifact.  Maybe something like "This document establishes rules and methods for defining and using enhanced code list artifacts with ..."

Current: 

> This document establishes methods for using code list artifacts with NIEM information exchange specifications. It provides for the use of Genericode documents, as well as for CSV code lists. It supports the use of code lists at run time and at schema definition time. It also includes identifiers for well-known columns that have semantics needed across the NIEM community.

**Comment by webb** [comment]
Added text to the introduction supporting 1 & 2.
Will stand down the requirement that Genericode files have a conformance target identifier in #15.
